INSERT INTO incidents (id, service, status, severity, initial_signal, signal_sources, blast_radius, rca_hypotheses, proposed_action, detected_at, resolved_at, jira_ticket_key) VALUES 
('INC-OOM-DEMO', 'food-orders', 'resolved', 'P3', 'OOMKilled crashloop on food-orders pods — memory limit reduced to 8Mi', '["chaos:k8s"]', '{"level": "medium", "reversible": true, "affected_services": ["food-orders"]}', '[]', 'null', NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days' + INTERVAL '10 minutes', 'KAN-101'),
('INC-CPU-DEMO', 'food-orders', 'resolved', 'P2', 'CPU Starvation on food-orders - latency spiked to 5s', '["chaos:k8s"]', '{"level": "high", "reversible": true, "affected_services": ["food-orders"]}', '[]', 'null', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days' + INTERVAL '25 minutes', 'KAN-102'),
('INC-SCALE-DEMO', 'food-orders', 'resolved', 'P1', 'Service Unavailable: food-orders scaled to zero', '["chaos:k8s"]', '{"level": "critical", "reversible": true, "affected_services": ["food-orders"]}', '[]', 'null', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days' + INTERVAL '5 minutes', 'KAN-103');

INSERT INTO postmortems (id, incident_id, title, summary, root_cause, impact, lessons_learned, timeline, corrective_actions, drafted_at, published_at, signed_off_by) VALUES 
('pm_1', 'INC-OOM-DEMO', 'OOMKilled CrashLoop on food-orders', 'The food-orders service experienced repeated OOMKilled events due to an aggressive memory limit reduction.', 'Memory limit was artificially constrained to 8Mi, causing the application to exceed its bounds immediately upon startup.', '500 users affected, 0 downtime (handled by healthy replicas).', 'Ensure memory limits are set appropriately based on historical usage data. Implement alerts for pods approaching memory limits before they OOM.', '[]', '[{"description": "Review and update memory limits for all tier-1 services", "owner": "sre-team", "status": "done", "jira_ticket": "KAN-101"}]', NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days', 'demo_user'),
('pm_2', 'INC-CPU-DEMO', 'CPU Starvation on food-orders', 'The food-orders service experienced severe CPU throttling, leading to high latency and request timeouts.', 'A background task consumed all available CPU shares, starving the main request handling threads.', '1200 users experienced slow load times, 5 minutes of degraded service.', 'Implement CPU limits to prevent single processes from starving the entire node. Add timeouts to background tasks.', '[]', '[{"description": "Implement strict CPU quotas on background workers", "owner": "platform-team", "status": "in_progress", "jira_ticket": "KAN-102"}]', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days', 'demo_user'),
('pm_3', 'INC-SCALE-DEMO', 'Service Unavailable: food-orders scaled to zero', 'The food-orders service became completely unavailable after being scaled down to 0 replicas.', 'An erroneous HPA configuration or manual intervention scaled the deployment to zero.', 'Complete outage for food-orders for 2 minutes.', 'Implement safeguards against scaling critical services to zero. Review HPA minimum replica settings.', '[]', '[{"description": "Audit HPA configurations for minimum replica counts", "owner": "sre-team", "status": "todo", "jira_ticket": "KAN-103"}]', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', 'demo_user');

INSERT INTO incident_events (event_id, incident_id, event_type, version, occurred_at, caused_by, payload) VALUES
('ev_1', 'INC-OOM-DEMO', 'IncidentResolved', 1, NOW() - INTERVAL '2 days', 'agent', '{"resolution_time_seconds": 600}'),
('ev_2', 'INC-CPU-DEMO', 'IncidentResolved', 1, NOW() - INTERVAL '5 days', 'agent', '{"resolution_time_seconds": 1500}'),
('ev_3', 'INC-SCALE-DEMO', 'IncidentResolved', 1, NOW() - INTERVAL '10 days', 'demo_user', '{"resolution_time_seconds": 300}');
