alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  resources:
    requests: { cpu: 20m, memory: 64Mi }
    limits: { cpu: 100m, memory: 128Mi }
server:
  retention: 6h
  global:
    scrape_interval: 30s
    evaluation_interval: 30s
  persistentVolume:
    size: 4Gi
  resources:
    requests: { cpu: 50m, memory: 250Mi }
    limits: { cpu: 250m, memory: 500Mi }
  service:
    type: ClusterIP
  extraScrapeConfigs: |
    - job_name: 'sre-pods'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_label_app]
          target_label: service
