from __future__ import annotations

from typing import Protocol

from sre_agent.domain.entities.app import App, AppId
from sre_agent.domain.entities.project import Project, ProjectId
from sre_agent.domain.value_objects import ServiceName


class ProjectRepository(Protocol):
    async def add(self, project: Project) -> None: ...
    async def get(self, project_id: ProjectId) -> Project | None: ...
    async def get_by_key(self, key: str) -> Project | None: ...
    async def save(self, project: Project) -> None: ...
    async def delete(self, project_id: ProjectId) -> None: ...
    async def list_all(self) -> list[Project]: ...


class AppRepository(Protocol):
    async def add(self, app: App) -> None: ...
    async def get(self, app_id: AppId) -> App | None: ...
    async def get_by_name(self, name: ServiceName) -> App | None: ...
    async def save(self, app: App) -> None: ...
    async def delete(self, app_id: AppId) -> None: ...
    async def list_all(self) -> list[App]: ...
    async def list_by_project(self, project_id: ProjectId) -> list[App]: ...
    async def list_by_namespace(self, namespace: str) -> list[App]: ...
