from __future__ import annotations

from typing import Protocol

from sre_agent.domain.entities.sla_tracker import SLATracker, SLATrackerId, SLAType
from sre_agent.domain.value_objects import IncidentId


class SLATrackerRepository(Protocol):
    async def add(self, tracker: SLATracker) -> None: ...
    async def get(self, tracker_id: SLATrackerId) -> SLATracker | None: ...
    async def save(self, tracker: SLATracker) -> None: ...
    async def list_for_incident(self, incident_id: IncidentId) -> list[SLATracker]: ...
    async def get_for_incident_and_type(
        self, incident_id: IncidentId, sla_type: SLAType
    ) -> SLATracker | None: ...
    async def list_open(self) -> list[SLATracker]: ...
