apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-payments
  namespace: demo-store
spec:
  action: delay
  mode: all
  selector:
    namespaces: [demo-store]
    labelSelectors:
      app: payments-api
  delay:
    latency: "1500ms"
    jitter: "100ms"
  duration: "3m"
