apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-payments
  namespace: demo-store
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces: [demo-store]
    labelSelectors:
      app: payments-api
